baseURL = "https://www.baradhiren.com/"
languageCode = "en-us"
title = "Supermoeth"
disqusShortname = "https-www-baradhiren-com"
copyright = "Hiren Barad" # cactus will use title if copyright is not set
theme = "cactus"

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Now"
url = "/now"
weight = 2

[[menu.main]]
name = "Writings"
url = "/posts"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[menu.main]]
name = "About"
url = "/about"
weight = 5

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

[params]

  colortheme = "dark" # dark, light, white, or classic
  rss = false # generate rss feed. default value is false
  googleAnalytics = "G-YSWNYMZ3JX"
  googleAnalyticsAsync = false # use asynchronous tracking. Synchronous tracking by default

  # Home page settings
  description = ""
  mainSection = "posts" # your main section
  showAllPostsOnHomePage = false # default
  postsOnHomePage = 5 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = true # show tags overview by default.
  showProjectsList = true # show projects list by default (if projects data file exists).
  projectsUrl = "https://github.com/baradhiren" # title link for projects list

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "January 2, 2006"

  # Post page settings
  show_updated = false # default
  showReadTime = true # default

  [params.comments]
    enabled = true # default
    engine = "disqus" # more supported engines will be added.

  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands
  [[params.social]]
    name = "github"
    link = "https://github.com/baradhiren"
  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/hiren-barad-970884a2/"
  [[params.social]]
    name = "email"
    link = "baradhiren@hotmail.com"  # no need for "mailto:" in the head